### ISSUE TITLE
Journal Notes

### ISSUE THREAD

**Issue by Caboose6130** [friendlysgames/Curse-of-Strahd-Reloaded#1]
All journal notes on all death house scenes seem to open to the general A2 journal entry, instead of the (assumed) specific notes for that section.

**Comment by Caboose6130** [comment]
Issue seems to be resolved, must have been on my end but links are working as expected

**Comment by friendlysgames** [comment]
Solved for next release, added [Journal Anchor Links](https://github.com/aMediocreDad/jal) as a dependency.
