### ISSUE TITLE
Can't install module in linux/docker. Error while installing: Cannot read properties of null (reading 'protected').  

### ISSUE THREAD

**Issue by omarbaza** [friendlysgames/Curse-of-Strahd-Reloaded#10]
Seems that uppercase and lowercase are blocking the installation from succeeding.

The error.log says

{"level":"error","message":"Metadata validation failed for module \"curse-of-strahd-reloaded\": The file \"scripts/cos-r.js\" included by module curse-of-strahd-reloaded does not exist"

The solution is:
1) Copied the whole package folder into my modules folder
2) Renamed folder from Scripts to scripts
3) Restarted server
4) Now, the module is detected and properly installed 

So you have some options:
1) change from scripts to Scripts in the .json or rename the folder to scripts and don't change the json
2) Maybe consider have every single folder in the module as lowercase? that's what ppl usually do to avoid this linux/windows problems (that and the folders as /)

**Comment by friendlysgames** [comment]
solved - prerelease.5
