### ISSUE TITLE
Loot Boxes  (feedback / some changes needed)

### ISSUE THREAD

**Issue by omarbaza** [friendlysgames/Curse-of-Strahd-Reloaded#12]
- 1F
	- [3. Den of Wolves](https://www.dndbeyond.com/sources/cos/appendix-b-death-house#3DenofWolves)
		- The cabinets location is swapped, the names are correct. (considering the map orientation and the entrance to the house in the south)
		- There are 3 batches of 20 bolts for each weapon. For the Silver bolts, should be 51/9 instead of 57/3 ?
			- The Silvered bolts, have not set the *Silvered* property (Details -> Silvered)
- 2F
	- [9. Secret Room](https://www.dndbeyond.com/sources/cos/appendix-b-death-house#9SecretRoom)
		- Missing *Signed Will*
- 3F
	- [12. Master Suite](https://www.dndbeyond.com/sources/cos/appendix-b-death-house#12MasterSuite)
		- Missing *grain -> roll of parchment* 
- Dungeon
	- [25. Well and Cultist Quarters](### 25. Well and Cultist Quarters)
		- Book bound in grimy black leather
			- Missing the list of names from the description
	- [34. Cult Leaders’ Quarters](https://www.dndbeyond.com/sources/cos/appendix-b-death-house#34CultLeadersQuarters)
		- Change *Hold Person* -> *Identify*

**Comment by friendlysgames** [comment]
Solved
